package http

import (
	"fmt"
	"slices"
	"strconv"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/multiselect"
	"bgscan/internal/ui/components/basic/input/selectinput"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/input/toggleinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/layout"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
	"charm.land/huh/v2"
)

const (
	groupHTTP         = "HTTP Settings"
	groupAdvanceHTTPS = "HTTP Advanced"
)

// statusGroups maps each group label to all standard HTTP status codes it covers.
var statusGroups = map[string][]int{
	"1xx": {100, 101, 102, 103},
	"2xx": {200, 201, 202, 203, 204, 205, 206, 207, 208, 226},
	"3xx": {300, 301, 302, 303, 304, 305, 306, 307, 308},
	"4xx": {
		400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
		410, 411, 412, 413, 414, 415, 416, 417, 418,
		421, 422, 423, 424, 425, 426, 428, 429, 431, 451,
	},
	"5xx": {500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511},
}

// groupOrder defines the display order for status code groups.
var groupOrder = []string{"1xx", "2xx", "3xx", "4xx", "5xx"}

// groupLabels provides human-readable labels for status code groups.
var groupLabels = map[string]string{
	"1xx": "1xx  Informational",
	"2xx": "2xx  Success",
	"3xx": "3xx  Redirection",
	"4xx": "4xx  Client Error",
	"5xx": "5xx  Server Error",
}

// Descriptions for UI fields.
const (
	descWorkers            = "The number of concurrent workers performing HTTP requests. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descHost               = "The target host or URL path used for the HTTP request. Can include a path (e.g., example.com/path), but the Host header will always use only the domain part."
	descServerName         = "Optional TLS Server Name Indication (SNI) override. If left empty, the domain from the host field is used automatically."
	descPort               = "The target port for the HTTP/HTTPS connection (e.g., 80 for HTTP, 443 for HTTPS)."
	descProtocol           = "The application protocol to use for the scan: 'http' or 'https'."
	descHTTPVersion        = "The HTTP protocol version used for requests: HTTP/1.1, HTTP/2, both (HTTP/1.1 + HTTP/2 with automatic negotiation), or HTTP/3 over QUIC."
	descTLSValidation      = "Enables strict TLS certificate validation when using HTTPS. If disabled, invalid, expired, or self-signed certificates are accepted."
	descMinTLSVersion      = "The minimum TLS version allowed for HTTPS connections. Connections attempting to negotiate a lower version will be rejected."
	descMaxTLSVersion      = "The maximum TLS version allowed for HTTPS connections. Limits the highest TLS version the scanner will attempt to negotiate."
	descTimeout            = "Maximum duration in milliseconds to wait for an HTTP response. Requests failing to complete within this window are considered failed."
	descPrefixOutput       = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
	descStatusCodeGroups   = "Select which HTTP status code groups count as a successful ('alive') result. Selecting a group adds all codes in that range; deselecting removes them all."
	descStatusCodeSpecific = "Fine-tune which specific status codes within the selected groups are accepted. Only codes belonging to an active group are shown here."
)

// Model represents the HTTP settings inspector component.
type Model struct {
	layout    *layout.Layout
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

// saveHTTP saves the current HTTP configuration and returns a notification command on error.
func saveHTTP(l *layout.Layout, cfg *config.HTTPConfig) tea.Cmd {
	if err := config.SaveHTTPConfig(cfg); err != nil {
		return notice.NewNoticeCmd(l, "Failed to save HTTP settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

// newIntInput creates a text input for integer values with validation and auto-save.
func newIntInput(l *layout.Layout, title string, value int, validateFn func(int) error, setFn func(int), saveFn func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			return validateFn(n)
		}),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			setFn(n)
			return saveFn()
		}),
	)
}

// newDurationInput creates a text input for duration values (in ms) with validation and auto-save.
func newDurationInput(l *layout.Layout, title string, value time.Duration, validateFn func(time.Duration) error, setFn func(time.Duration), saveFn func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			return validateFn(time.Duration(n) * time.Millisecond)
		}),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			setFn(time.Duration(n) * time.Millisecond)
			return saveFn()
		}),
	)
}

// newStringInput creates a text input for string values with validation and auto-save.
func newStringInput(l *layout.Layout, title, value string, validateFn func(string) error, setFn func(string), saveFn func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(value),
		textinput.WithValidation(validateFn),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			setFn(v)
			return saveFn()
		}),
	)
}

// ── Status Code Helpers ────────────────────────────────────────────────

// codesFromGroups expands a list of group names (e.g., ["2xx"]) into a flat list of status codes.
func codesFromGroups(groups []string) []int {
	count := 0
	for _, g := range groups {
		count += len(statusGroups[g])
	}
	out := make([]int, 0, count)
	for _, g := range groups {
		out = append(out, statusGroups[g]...)
	}
	return out
}

// filterCodesByGroup returns only the codes from the input slice that belong to the specified group.
func filterCodesByGroup(codes []int, group string) []int {
	groupCodes := statusGroups[group]
	set := make(map[int]struct{}, len(codes))
	for _, c := range codes {
		set[c] = struct{}{}
	}

	cs := make([]int, 0, 4)
	for _, c := range groupCodes {
		if _, ok := set[c]; ok {
			cs = append(cs, c)
		}
	}
	return cs
}

// groupIsActive checks if any code from the given group exists in the provided list.
func groupIsActive(codes []int, group string) bool {
	set := make(map[int]struct{}, len(codes))
	for _, c := range codes {
		set[c] = struct{}{}
	}
	for _, c := range statusGroups[group] {
		if _, ok := set[c]; ok {
			return true
		}
	}
	return false
}

// groupsChanged compares two slices of group names to detect changes.
func groupsChanged(old, new []string) bool {
	if len(old) != len(new) {
		return true
	}
	oldSet := make(map[string]struct{}, len(old))
	for _, g := range old {
		oldSet[g] = struct{}{}
	}
	for _, g := range new {
		if _, ok := oldSet[g]; !ok {
			return true
		}
	}
	return false
}

// buildSpecificOptions creates huh options for a specific status code group.
func buildSpecificOptions(group string) []huh.Option[int] {
	codes := statusGroups[group]
	opts := make([]huh.Option[int], len(codes))
	for i, c := range codes {
		opts[i] = huh.NewOption(strconv.Itoa(c), c)
	}
	return opts
}

// filterCodesByActiveGroups returns codes that belong to one of the active groups.
func filterCodesByActiveGroups(codes []int, activeGroups []string) []int {
	active := make(map[string]struct{}, len(activeGroups))
	for _, g := range activeGroups {
		active[g] = struct{}{}
	}

	var out []int
	for _, c := range codes {
		for g, groupCodes := range statusGroups {
			if _, ok := active[g]; !ok {
				continue
			}
			if slices.Contains(groupCodes, c) {
				out = append(out, c)
				break
			}
		}
	}
	return out
}

// groupStatusCodes categorizes a flat list of status codes into their respective groups.
// If the list is empty, it returns all standard groups.
func groupStatusCodes(codes []int) map[string][]int {
	if len(codes) == 0 {
		// Return a copy to prevent mutation
		res := make(map[string][]int, len(statusGroups))
		for k, v := range statusGroups {
			res[k] = append([]int(nil), v...)
		}
		return res
	}

	groups := map[string][]int{
		"1xx": {},
		"2xx": {},
		"3xx": {},
		"4xx": {},
		"5xx": {},
	}

	for _, code := range codes {
		switch code / 100 {
		case 1:
			groups["1xx"] = append(groups["1xx"], code)
		case 2:
			groups["2xx"] = append(groups["2xx"], code)
		case 3:
			groups["3xx"] = append(groups["3xx"], code)
		case 4:
			groups["4xx"] = append(groups["4xx"], code)
		case 5:
			groups["5xx"] = append(groups["5xx"], code)
		}
	}

	// Remove empty groups
	for k, v := range groups {
		if len(v) == 0 {
			delete(groups, k)
		}
	}

	return groups
}

// ── Model Construction ────────────────────────────────────────────────

// New creates a new HTTP settings inspector model.
func New(l *layout.Layout, name string) *Model {
	cfg := config.GetHTTP()
	save := func() tea.Cmd { return saveHTTP(l, cfg) }

	m := &Model{
		layout: l,
		name:   name,
		id:     ui.NewComponentID(),
	}

	// Validation helper closure
	valField := func(tmp *config.HTTPConfig, field string) func(string) error {
		return func(v string) error {
			return fieldErr(validate.ValidateHTTP(tmp), field)
		}
	}

	// ─── Easy settings ───
	workers := newIntInput(l, "Enter number of workers", cfg.Workers,
		func(n int) error {
			tmp := *cfg
			tmp.Workers = n
			return valField(&tmp, "Workers")("")
		},
		func(n int) { cfg.Workers = n }, save)

	host := newStringInput(l, "Enter target host", cfg.Host,
		func(v string) error {
			tmp := *cfg
			tmp.Host = v
			return valField(&tmp, "Host")("")
		}, func(v string) { cfg.Host = v }, save)

	serverName := newStringInput(l, "Enter server name (SNI)", cfg.ServerName,
		func(v string) error {
			tmp := *cfg
			tmp.ServerName = v
			return valField(&tmp, "ServerName")("")
		}, func(v string) { cfg.ServerName = v }, save)

	port := newIntInput(l, "Enter HTTP port", cfg.Port,
		func(n int) error {
			tmp := *cfg
			tmp.Port = n
			return valField(&tmp, "Port")("")
		}, func(n int) { cfg.Port = n }, save)

	protocol := selectinput.New(
		l, "Protocol",
		selectinput.WithValue(cfg.Protocol),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("HTTP", "http"),
			huh.NewOption("HTTPS", "https"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.Protocol = v
			return save()
		}),
	)

	httpVersion := selectinput.New(
		l, "HTTP Version",
		selectinput.WithValue(cfg.Version),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("HTTP/1.1", "h1"),
			huh.NewOption("HTTP/2", "h2"),
			huh.NewOption("HTTP/1.1 + HTTP/2", "h1,h2"),
			huh.NewOption("HTTP/3 (QUIC)", "h3"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.Version = v
			return save()
		}),
	)

	tlsValidation := toggleinput.New(
		l, "TLS Validation",
		toggleinput.WithValue(cfg.TLSValidation),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			cfg.TLSValidation = v
			return save()
		}),
	)

	timeout := newDurationInput(l, "Enter timeout (milliseconds)", cfg.Timeout.Duration(),
		func(d time.Duration) error {
			tmp := *cfg
			tmp.Timeout = config.NewDurationMS(d)
			return valField(&tmp, "Timeout")("")
		},
		func(d time.Duration) { cfg.Timeout = config.NewDurationMS(d) }, save)

	prefixOutput := newStringInput(l, "Enter output file prefix", cfg.PrefixOutput,
		func(v string) error {
			tmp := *cfg
			tmp.PrefixOutput = v
			return valField(&tmp, "PrefixOutput")("")
		}, func(v string) { cfg.PrefixOutput = v }, save)

	// ─── Advanced settings ───
	minTLSVersion := selectinput.New(
		l, "Min TLS Version",
		selectinput.WithValue(cfg.MinTLSVersion),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("TLS 1.0", "tls1.0"),
			huh.NewOption("TLS 1.1", "tls1.1"),
			huh.NewOption("TLS 1.2", "tls1.2"),
			huh.NewOption("TLS 1.3", "tls1.3"),
		),
		selectinput.WithValidation(func(v string) error {
			tmp := *cfg
			tmp.MinTLSVersion = v
			return valField(&tmp, "MinTLSVersion")("")
		}),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.MinTLSVersion = v
			return save()
		}),
	)

	maxTLSVersion := selectinput.New(
		l, "Max TLS Version",
		selectinput.WithValue(cfg.MaxTLSVersion),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("TLS 1.0", "tls1.0"),
			huh.NewOption("TLS 1.1", "tls1.1"),
			huh.NewOption("TLS 1.2", "tls1.2"),
			huh.NewOption("TLS 1.3", "tls1.3"),
		),
		selectinput.WithValidation(func(v string) error {
			tmp := *cfg
			tmp.MaxTLSVersion = v
			return valField(&tmp, "MaxTLSVersion")("")
		}),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.MaxTLSVersion = v
			return save()
		}),
	)

	// ─── Status Code Configuration ───
	initGroup := groupStatusCodes(cfg.AcceptedStatusCodes)
	groupMultiselectValue := make([]string, 0, len(initGroup))
	for k := range initGroup {
		groupMultiselectValue = append(groupMultiselectValue, k)
	}

	groupOpts := make([]huh.Option[string], len(groupOrder))
	for i, g := range groupOrder {
		groupOpts[i] = huh.NewOption(groupLabels[g], g)
	}

	statusCodeGroups := multiselect.New(
		l, "Select accepted status code groups",
		multiselect.WithFocus[string](),
		multiselect.WithOptions(groupOpts...),
		multiselect.WithValue(groupMultiselectValue),
		multiselect.WithRequired[string](),
		multiselect.WithOnSubmit(func(selected []string) tea.Cmd {
			if !groupsChanged(groupMultiselectValue, selected) {
				return nil
			}

			cfg.AcceptedStatusCodes = codesFromGroups(selected)
			groupMultiselectValue = selected
			return save()
		}),
	)

	// Build per-group specific code selectors.
	var statusCodeSpecificFields []inspector.Field

	for _, g := range groupOrder {
		group := g

		specific := multiselect.New(
			l,
			fmt.Sprintf("Fine-tune %s codes", groupLabels[group]),
			multiselect.WithFocus[int](),
			multiselect.WithOptions(buildSpecificOptions(group)...),
			multiselect.WithValue(initGroup[g]),
			multiselect.WithRequired[int](),
			multiselect.WithOnSubmit(func(selected []int) tea.Cmd {
				otherGroups := filterCodesByActiveGroups(cfg.AcceptedStatusCodes, groupMultiselectValue)
				cfg.AcceptedStatusCodes = append(otherGroups, selected...)
				return save()
			}),
		)

		statusCodeGroups.AppendOnSubmit(func() tea.Cmd {
			specific.SetValue(filterCodesByGroup(cfg.AcceptedStatusCodes, group))
			return m.refresh()
		})

		// Capture group variable for closure
		currentGroup := group
		visible := func() bool {
			return slices.Contains(groupMultiselectValue, currentGroup)
		}

		statusCodeSpecificFields = append(statusCodeSpecificFields, inspector.Field{
			Name:        fmt.Sprintf("Accepted %s Codes", group),
			Description: fmt.Sprintf("Select which %s codes count as successful.", groupLabels[group]),
			Group:       groupAdvanceHTTPS,
			Input:       inspector.Adapt(specific),
			Visible:     visible,
			Format:      inspector.FormatIntList,
		})
	}

	// Visibility predicates
	isHTTPS := func() bool { return cfg.Protocol == "https" }
	isStrictTLS := func() bool { return isHTTPS() && cfg.TLSValidation && !isHTTP3(cfg.Version) }

	// ─── Field Assembly ───
	fields := []inspector.Field{
		// Easy settings (always visible)
		{Name: "Workers", Description: descWorkers, Group: groupHTTP, Input: inspector.Adapt(workers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Host", Description: descHost, Group: groupHTTP, Input: inspector.Adapt(host), Visible: alwaysVisible},
		{Name: "Port", Description: descPort, Group: groupHTTP, Input: inspector.Adapt(port), Visible: alwaysVisible},
		{Name: "Protocol", Description: descProtocol, Group: groupHTTP, Input: inspector.Adapt(protocol), Visible: alwaysVisible},
		{Name: "HTTP Version", Description: descHTTPVersion, Group: groupHTTP, Input: inspector.Adapt(httpVersion), Visible: isHTTPS},
		{Name: "Timeout", Description: descTimeout, Group: groupHTTP, Input: inspector.Adapt(timeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "TLS Validation", Description: descTLSValidation, Group: groupHTTP, Input: inspector.Adapt(tlsValidation), Visible: isHTTPS, Format: inspector.FormatBool},

		// Advanced settings
		{Name: "Server Name SNI", Description: descServerName, Group: groupAdvanceHTTPS, Input: inspector.Adapt(serverName), Visible: isHTTPS},
		{Name: "Min TLS Version", Description: descMinTLSVersion, Group: groupAdvanceHTTPS, Input: inspector.Adapt(minTLSVersion), Visible: isStrictTLS},
		{Name: "Max TLS Version", Description: descMaxTLSVersion, Group: groupAdvanceHTTPS, Input: inspector.Adapt(maxTLSVersion), Visible: isStrictTLS},
		{Name: "Prefix Output", Description: descPrefixOutput, Group: groupAdvanceHTTPS, Input: inspector.Adapt(prefixOutput), Visible: alwaysVisible},
		{Name: "Status Code Groups", Description: descStatusCodeGroups, Group: groupAdvanceHTTPS, Input: inspector.Adapt(statusCodeGroups), Visible: alwaysVisible, Format: inspector.FormatStringList},
	}

	fields = append(fields, statusCodeSpecificFields...)

	m.inspector = inspector.New(l, "http settings", fields)
	return m
}

func alwaysVisible() bool { return true }

func fieldErr(errs map[string]error, field string) error {
	if errs == nil {
		return nil
	}
	return errs[field]
}

func isHTTP3(v string) bool {
	return v == "h3" || v == "http3"
}

func (m *Model) refresh() tea.Cmd {
	if m.inspector != nil {
		if ins, ok := m.inspector.(*inspector.Model); ok {
			return ins.Refresh()
		}
	}
	return nil
}
