package http

import (
	"strconv"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/selectinput"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/input/toggleinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/layout"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
	"charm.land/huh/v2"
)

const groupHTTP = "HTTP Settings"

const (
	tls10 = "tls1.0"
	tls11 = "tls1.1"
	tls12 = "tls1.2"
	tls13 = "tls1.3"
)

const (
	descWorkers       = "The number of concurrent workers performing HTTP requests. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descHost          = "The target host or URL path used for the HTTP request. Can include a path (e.g., example.com/path), but the Host header will always use only the domain part."
	descServerName    = "Optional TLS Server Name Indication (SNI) override. If left empty, the domain from the host field is used automatically."
	descPort          = "The target port for the HTTP/HTTPS connection (e.g., 80 for HTTP, 443 for HTTPS)."
	descProtocol      = "The application protocol to use for the scan: 'http' or 'https'."
	descTLSValidation = "Enables strict TLS certificate validation when using HTTPS. If disabled, invalid, expired, or self-signed certificates are accepted."
	descMinTLSVersion = "The minimum TLS version allowed for HTTPS connections. Connections attempting to negotiate a lower version will be rejected."
	descMaxTLSVersion = "The maximum TLS version allowed for HTTPS connections. Limits the highest TLS version the scanner will attempt to negotiate."
	descTimeout       = "Maximum duration in milliseconds to wait for an HTTP response. Requests failing to complete within this window are considered failed."
	descPrefixOutput  = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
)

type Model struct {
	layout    *layout.Layout
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveHTTP(l *layout.Layout, cfg *config.HTTPConfig) tea.Cmd {
	if err := config.SaveHTTPConfig(cfg); err != nil {
		return notice.NewNoticeCmd(l, "Failed to save HTTP settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func intInput(l *layout.Layout, title string, value int, val func(string) error, set func(int), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(n)
			return save()
		}),
	)
}

func durationMSInput(l *layout.Layout, title string, value time.Duration, val func(string) error, set func(time.Duration), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(time.Duration(n) * time.Millisecond)
			return save()
		}),
	)
}

func stringInput(l *layout.Layout, title, value string, val func(string) error, set func(string), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(value),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			set(v)
			return save()
		}),
	)
}

func New(l *layout.Layout, name string) *Model {
	cfg := config.GetHTTP()
	save := func() tea.Cmd { return saveHTTP(l, cfg) }

	workers := intInput(l, "Enter number of workers", cfg.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Workers = n
			return fieldErr(validate.ValidateHTTP(&tmp), "Workers")
		},
		func(n int) { cfg.Workers = n }, save)

	host := stringInput(l, "Enter target host", cfg.Host,
		func(v string) error {
			tmp := *cfg
			tmp.Host = v
			return fieldErr(validate.ValidateHTTP(&tmp), "Host")
		},
		func(v string) { cfg.Host = v }, save)

	serverName := stringInput(l, "Enter server name (SNI)", cfg.ServerName,
		func(v string) error {
			tmp := *cfg
			tmp.ServerName = v
			return fieldErr(validate.ValidateHTTP(&tmp), "ServerName")
		},
		func(v string) { cfg.ServerName = v }, save)

	port := intInput(l, "Enter HTTP port", cfg.Port,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Port = n
			return fieldErr(validate.ValidateHTTP(&tmp), "Port")
		},
		func(n int) { cfg.Port = n }, save)

	protocol := selectinput.New(
		l, "Protocol",
		selectinput.WithValue(cfg.Protocol),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("HTTP", "http"),
			huh.NewOption("HTTPS", "https"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.Protocol = v
			return save()
		}),
	)

	tlsValidation := toggleinput.New(
		l, "TLS Validation",
		toggleinput.WithValue(cfg.TLSValidation),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			cfg.TLSValidation = v
			return save()
		}),
	)

	minTLSVersion := selectinput.New(
		l, "Min TLS Version",
		selectinput.WithValue(cfg.MinTLSVersion),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("TLS 1.0", tls10),
			huh.NewOption("TLS 1.1", tls11),
			huh.NewOption("TLS 1.2", tls12),
			huh.NewOption("TLS 1.3", tls13),
		),
		selectinput.WithValidation(func(v string) error {
			tmp := *cfg
			tmp.MinTLSVersion = v
			return fieldErr(validate.ValidateHTTP(&tmp), "MinTLSVersion")
		}),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.MinTLSVersion = v
			return save()
		}),
	)

	maxTLSVersion := selectinput.New(
		l, "Max TLS Version",
		selectinput.WithValue(cfg.MaxTLSVersion),
		selectinput.WithFocus[string](),
		selectinput.WithValidation(func(v string) error {
			tmp := *cfg
			tmp.MaxTLSVersion = v
			return fieldErr(validate.ValidateHTTP(&tmp), "MaxTLSVersion")
		}),
		selectinput.WithOptions(
			huh.NewOption("TLS 1.0", tls10),
			huh.NewOption("TLS 1.1", tls11),
			huh.NewOption("TLS 1.2", tls12),
			huh.NewOption("TLS 1.3", tls13),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.MaxTLSVersion = v
			return save()
		}),
	)

	timeout := durationMSInput(l, "Enter timeout (milliseconds)", cfg.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateHTTP(&tmp), "Timeout")
		},
		func(d time.Duration) { cfg.Timeout = config.NewDurationMS(d) }, save)

	prefixOutput := stringInput(l, "Enter output file prefix", cfg.PrefixOutput,
		func(v string) error {
			tmp := *cfg
			tmp.PrefixOutput = v
			return fieldErr(validate.ValidateHTTP(&tmp), "PrefixOutput")
		},
		func(v string) { cfg.PrefixOutput = v }, save)

	httpsOnly := func() bool { return cfg.Protocol == "https" }
	tlsOnly := func() bool { return httpsOnly() && cfg.TLSValidation }

	fields := []inspector.Field{
		{Name: "Workers", Description: descWorkers, Group: groupHTTP, Input: inspector.Adapt(workers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Host", Description: descHost, Group: groupHTTP, Input: inspector.Adapt(host), Visible: alwaysVisible},
		{Name: "Port", Description: descPort, Group: groupHTTP, Input: inspector.Adapt(port), Visible: alwaysVisible},
		{Name: "Protocol", Description: descProtocol, Group: groupHTTP, Input: inspector.Adapt(protocol), Visible: alwaysVisible},
		{Name: "Timeout", Description: descTimeout, Group: groupHTTP, Input: inspector.Adapt(timeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "TLS Validation", Description: descTLSValidation, Group: groupHTTP, Input: inspector.Adapt(tlsValidation), Visible: httpsOnly, Format: inspector.FormatBool},
		{Name: "Min TLS Version", Description: descMinTLSVersion, Group: groupHTTP, Input: inspector.Adapt(minTLSVersion), Visible: tlsOnly},
		{Name: "Max TLS Version", Description: descMaxTLSVersion, Group: groupHTTP, Input: inspector.Adapt(maxTLSVersion), Visible: tlsOnly},
		{Name: "Server Name SNI", Description: descServerName, Group: groupHTTP, Input: inspector.Adapt(serverName), Visible: httpsOnly},
		{Name: "Prefix Output", Description: descPrefixOutput, Group: groupHTTP, Input: inspector.Adapt(prefixOutput), Visible: alwaysVisible},
	}

	return &Model{
		layout:    l,
		name:      name,
		id:        ui.NewComponentID(),
		inspector: inspector.New(l, "http settings", fields),
	}
}

func alwaysVisible() bool { return true }

func fieldErr(errs map[string]error, field string) error {
	return errs[field]
}
