package tcp

import (
	"strconv"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/layout"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
)

const groupTCP = "TCP Settings"

const (
	descWorkers      = "The number of concurrent workers performing TCP connection attempts. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descPort         = "The target TCP port to probe on each IP address. The scanner attempts to establish a TCP connection to this port."
	descTimeout      = "Maximum duration in milliseconds to wait for a TCP connection to be established. Targets failing to respond within this window are considered unreachable."
	descTries        = "The maximum number of retry attempts per target to mitigate connection failures. Higher values improve reliability but increase total scan duration."
	descPrefixOutput = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
)

type Model struct {
	layout    *layout.Layout
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveTCP(l *layout.Layout, cfg *config.TCPConfig) tea.Cmd {
	if err := config.SaveTCPConfig(cfg); err != nil {
		return notice.NewNoticeCmd(l, "Failed to save TCP settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func intInput(l *layout.Layout, title string, value int, validate func(string) error, set func(int), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(validate),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(n)
			return save()
		}),
	)
}

func durationMSInput(l *layout.Layout, title string, value time.Duration, validate func(string) error, set func(time.Duration), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(validate),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(time.Duration(n) * time.Millisecond)
			return save()
		}),
	)
}

func stringInput(l *layout.Layout, title, value string, validate func(string) error, set func(string), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(value),
		textinput.WithValidation(validate),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			set(v)
			return save()
		}),
	)
}

func New(l *layout.Layout, name string) *Model {
	cfg := config.GetTCP()
	save := func() tea.Cmd { return saveTCP(l, cfg) }

	workers := intInput(l, "Enter number of workers", cfg.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Workers = n
			return fieldErr(validate.ValidateTCP(&tmp), "Workers")
		},
		func(n int) { cfg.Workers = n }, save)

	port := intInput(l, "Enter TCP port", cfg.Port,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Port = n
			return fieldErr(validate.ValidateTCP(&tmp), "Port")
		},
		func(n int) { cfg.Port = n }, save)

	timeout := durationMSInput(l, "Enter timeout (milliseconds)", cfg.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateTCP(&tmp), "Timeout")
		},
		func(d time.Duration) { cfg.Timeout = config.NewDurationMS(d) }, save)

	tries := intInput(l, "Enter maximum attempts", int(cfg.Tries),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Tries = uint16(n)
			return fieldErr(validate.ValidateTCP(&tmp), "Tries")
		},
		func(n int) { cfg.Tries = uint16(n) }, save)

	prefixOutput := stringInput(l, "Enter output file prefix", cfg.PrefixOutput,
		func(v string) error {
			tmp := *cfg
			tmp.PrefixOutput = v
			return fieldErr(validate.ValidateTCP(&tmp), "PrefixOutput")
		},
		func(v string) { cfg.PrefixOutput = v }, save)

	fields := []inspector.Field{
		{Name: "Workers", Description: descWorkers, Group: groupTCP, Input: inspector.Adapt(workers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Port", Description: descPort, Group: groupTCP, Input: inspector.Adapt(port), Visible: alwaysVisible},
		{Name: "Timeout", Description: descTimeout, Group: groupTCP, Input: inspector.Adapt(timeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Tries", Description: descTries, Group: groupTCP, Input: inspector.Adapt(tries), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Prefix Output", Description: descPrefixOutput, Group: groupTCP, Input: inspector.Adapt(prefixOutput), Visible: alwaysVisible},
	}

	return &Model{
		layout:    l,
		name:      name,
		id:        ui.NewComponentID(),
		inspector: inspector.New(l, "tcp settings", fields),
	}
}

func alwaysVisible() bool { return true }

func fieldErr(errs map[string]error, field string) error {
	return errs[field]
}
